#!/bin/bash
#
# Copyright (C) 2020-2021 by UsergeTeam@Github, < https://github.com/UsergeTeam >.
#
# This file is part of < https://github.com/UsergeTeam/Userge > project,
# and is released under the "GNU v3.0 License Agreement".
# Please see < https://github.com/UsergeTeam/Userge/blob/master/LICENSE >
#
# All rights reserved.

mkdir -p /tmp/ && \
    cd /tmp/ && \
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    dpkg -i ./google-chrome-stable_current_amd64.deb; && \
    rm ./google-chrome-stable_current_amd64.deb && pip install jq

mkdir -p /tmp/ && \
    cd /tmp/ && \
    wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip && \
    unzip /tmp/chromedriver.zip chromedriver -d /usr/bin/ && \
    rm /tmp/chromedriver.zip && pip install -r requirements.txt

trap joinProc INT TERM

declare -i bgProc
declare -ir usr1=138
declare -r cmd='. init/init.sh; runUserge "$@"'

setProc() {
    bgProc=$1
}

waitProc() {
    wait $bgProc
}

killProc() {
    kill $bgProc &> /dev/null
}

joinProc() {
    if test $bgProc; then
        killProc
        waitProc
    fi
}

run() {
    joinProc
    bash -c "$cmd" $0 "$@" &
    setProc $!
    waitProc
    test $? -eq $usr1 && run "$@"
}

run "$@"
